### ISSUE TITLE
Python 2 to 3 Conversion: Unspecified Division

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/histogram#24]
The following files have unspecified division on the following lines:
* `/histogram/tests/histogram/Histogram_TestCase.py`: Lines 321, 322, 384, 389, 399, 404, 418, 426, 448, 502, 506, 509
* `/histogram/tests/histogram/NdArrayDataset_TestCase.py`: Lines 47, 58, 65, 78, 82, 86, 97, 101, 127, 128, 131, 143, 147, 166, 170, 188, 192, 224, 225, 228, 240, 243, 271, 285, 301, 316, 318, 366
* `/histogram/python/histogram/ContinuousAxisMapper.py`: Lines 47, 53, 56
* `/histogram/python/histogram/data_plotter.py`: Line 302
* `/histogram/python/histogram/Histogram.py`: Lines 319, 471, 472, 473, 482, 483, 486, 487, 489, 491, 568, 569, 570, 571, 580, 581, 937, 941
* `/histogram/python/histogram/__init__.py`: Lines 548, 732
* `/histogram/python/histogram/NdArrayDataset.py`: Lines 124, 216, 228, 233, 235, 248, 249, 251, 296, 310, 385, 387
* `/histogram/python/histogram/plotter.py`: Lines 225, 226, 235, 238, 239
* `/histogram/python/histogram/SimpleRebin.py`: Lines 10, 40, 77, 91

Additionally, there are some cases of unspecified division that depend on the following questions:
* `/histogram/tests/histogram/ValueWithError_TestCase.py`: What does `ValueWithError()` return (float or int)?
* `/histogram/tests/histogram/Axis.py`: What are `slicingInfo.start`, `slicingInfo.end`, and `self.unit()` (float or int)?
* `/histogram/python/histogram/ErrorPropagator.py`: What are `this._value` and `other._value`?
* `/histogram/python/histogram/EvenlyContinuousAxisMapper.py`: Does `bb` store floats or ints?

Finally, on line 217 of `/histogram/python/histogram/NdArrayDataset.py`, should the division be float or floor? The division is specified as floor, but it doesn't seem to fit with the rest of the code.

**Comment by yxqd** [comment]
I made divisions in these files explicit.

Some of the divisions are done to objects, not numbers, so they may look confusing. For example ValueWithError is an object that represents a measured value with which an error bar is associated.
