### ISSUE TITLE
Python 2 to 3 Conversion: Undefined Names

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/histogram#25]
In the following files, there are unspecified names (for functions or variables) that need to be resolved:
* `/histogram/obsolete/histograms/applications/gui/controllers/__init__.py`: `models` and `view` on line 22
* `/histogram/tests/histogram/dataplotter_TestCase.py`: `sortxy_x` on line 94 and `sortxys_x` on line 104
* `/histogram/tests/histogram/histogramTest_Histogram.py`: `ax3` on line 168
* `/histogram/tests/histogram/run_histogramTests.py`: `run()` on line 29

**Comment by yxqd** [comment]
* Please ignore problems under "obsolete"
* Please remove the "hidden" test methods _test_sortxy_x and _test_sortxys_x
* Sorry I did not see a problem here. Could you please include a link like this? https://github.com/danse-inelastic/histogram/blob/master/tests/histogram/histogramTest_Histogram.py#L168
* This script will be deleted
