### ISSUE TITLE
Python 2 to 3 Conversion: What's Left to Do

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/histogram#27]
The following things must still be done to finish converting this repository to Python 3:
* Update the files in the subdirectories in `/histogram/python/histogram` so that their support Python 3. These subdirectories are:
  * `/histogram/python/histogram/hdf`
  * `/histogram/python/histogram/ndarray`
  * `/histogram/python/histogram/pyrecomponents`
  * `/histogram/python/histogram/scripts`
* Run tests to confirm that histogram works in both Python 2 and 3

**Comment by yxqd** [comment]
done with dependencies: #36
